"""
LangGraph state definition.

Defines the state type used throughout the RAG pipeline graph.
Uses TypedDict for lightweight state passing between graph nodes.
"""

from __future__ import annotations

from typing import Any, TypedDict


class GraphState(TypedDict, total=False):
    """State of the RAG pipeline graph.

    This state is passed through all graph nodes and accumulates
    data as the pipeline progresses.

    Attributes:
        query: Original user query.
        rewritten_query: Query after LLM rewriting for better retrieval.
        search_results: Results from hybrid search (vector + BM25).
        classification: Result from PhoBERT classification.
        reranked_results: Results after reranking.
        context: Formatted context string for the LLM prompt (RAG context).
        answer: Final answer generated by the LLM.
        error: Error message if any node fails.
        metadata: Additional metadata for tracing/logging.

        # Web search fields
        web_search_needed: Whether web search is required.
        web_search_reason: Reason why web search is needed.
        web_search_results: Raw results from web search provider.
        web_context: Formatted web context string for the LLM prompt.
        merged_context: Combined RAG + web context string.
        source_mode: Source mode indicator (rag_only, web_only, rag_plus_web).
        citations: List of citation references.
    """

    query: str
    rewritten_query: str | None
    search_results: list[dict[str, Any]] | None
    classification: dict[str, Any] | None
    reranked_results: list[dict[str, Any]] | None
    context: str | None  # RAG context
    answer: str | None
    error: str | None
    metadata: dict[str, Any] | None

    # Web search fields
    web_search_needed: bool | None
    web_search_reason: str | None
    web_search_results: list[dict[str, Any]] | None
    web_context: str | None
    merged_context: str | None
    source_mode: str | None  # "rag_only", "web_only", "rag_plus_web"
    citations: list[dict[str, Any]] | None
