"""
LangGraph state definition.

Defines the state type used throughout the RAG pipeline graph.
Uses TypedDict for lightweight state passing between graph nodes.
"""

from __future__ import annotations

from typing import Any, TypedDict


class GraphState(TypedDict, total=False):
    """State of the RAG pipeline graph.

    This state is passed through all graph nodes and accumulates
    data as the pipeline progresses.

    Attributes:
        query: Original user query.
        rewritten_query: Query after LLM rewriting for better retrieval.
        search_results: Results from hybrid search (vector + BM25).
        classification: Result from PhoBERT classification.
        reranked_results: Results after reranking.
        context: Formatted context string for the LLM prompt.
        answer: Final answer generated by the LLM.
        error: Error message if any node fails.
        metadata: Additional metadata for tracing/logging.
    """

    query: str
    rewritten_query: str | None
    search_results: list[dict[str, Any]] | None
    classification: dict[str, Any] | None
    reranked_results: list[dict[str, Any]] | None
    context: str | None
    answer: str | None
    error: str | None
    metadata: dict[str, Any] | None
